package gazelle_ext

import (
	"context"
	_ "embed"
	"errors"
	"flag"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	sitter "github.com/smacker/go-tree-sitter"
	"github.com/smacker/go-tree-sitter/java"
)

const (
	languageName = "java"
	fileType     = ".java"
)

type Extension struct {
	parser *sitter.Parser
}

func NewLanguage() language.Language {
	parser := sitter.NewParser()
	parser.SetLanguage(java.GetLanguage())

	return &Extension{parser}
}

// RegisterFlags registers command-line flags used by the extension. This
// method is called once with the root configuration when Gazelle
// starts. RegisterFlags may set an initial values in Config.Exts. When flags
// are set, they should modify these values.
func (e *Extension) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
}

// CheckFlags validates the configuration after command line flags are parsed.
// This is called once with the root configuration when Gazelle starts.
// CheckFlags may set default values in flags or make implied changes.
func (e *Extension) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

// KnownDirectives returns a list of directive keys that this Configurer can
// interpret. Gazelle prints errors for directives that are not recoginized by
// any Configurer.
func (e *Extension) KnownDirectives() []string {
	return nil
}

// Configure modifies the configuration using directives and other information
// extracted from a build file. Configure is called in each directory.
//
// c is the configuration for the current directory. It starts out as a copy
// of the configuration for the parent directory.
//
// rel is the slash-separated relative path from the repository root to
// the current directory. It is "" for the root directory itself.
//
// f is the build file for the current directory or nil if there is no
// existing build file.
func (e *Extension) Configure(c *config.Config, rel string, f *rule.File) {
}

// Name returns the name of the language. This should be a prefix of the
// kinds of rules generated by the language, e.g., "go" for the Go extension
// since it generates "go_library" rules.
func (e *Extension) Name() string {
	return languageName
}

// Imports returns a list of ImportSpecs that can be used to import the rule
// r. This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (e *Extension) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	panic("not implemented") // TODO: Implement
}

// Embeds returns a list of labels of rules that the given rule embeds. If
// a rule is embedded by another importable rule of the same language, only
// the embedding rule will be indexed. The embedding rule will inherit
// the imports of the embedded rule.
func (e *Extension) Embeds(r *rule.Rule, from label.Label) []label.Label {
	panic("not implemented") // TODO: Implement
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each
// rule generated by language.GenerateRules in
// language.GenerateResult.Imports. Resolve generates a "deps" attribute (or
// the appropriate language-specific equivalent) for each import according to
// language-specific rules and heuristics.
func (e *Extension) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
	imps := imports.([]string)
	r.DelAttr("deps")
	if len(imps) == 0 {
		return
	}

	deps := make([]string, 0, len(imps))

	for _, imp := range imps {
		impLabel, err := label.Parse(imp)
		if err != nil {
			log.Printf("%s: import of %q is invalid: %v", from.String(), imp, err)
			continue
		}

		impLabel = impLabel.Abs(from.Repo, from.Pkg)

		if impLabel.Repo != "" || !c.IndexLibraries {
			// This is a dependency that is external to the current repo, or indexing
			// is disabled so take a guess at what hte target name should be.
			deps = append(deps, strings.TrimSuffix(imp, fileType))
			continue
		}

		res := resolve.ImportSpec{
			Lang: languageName,
			Imp:  impLabel.String(),
		}
		matches := ix.FindRulesByImportWithConfig(c, res, languageName)

		if len(matches) == 0 {
			log.Printf(
				"%s: %q (%s) was not found in dependency index. Skipping. This may result in an incomplete deps section and require manual BUILD file intervention.\n",
				from.String(),
				imp,
				impLabel.String(),
			)
		}

		for _, m := range matches {
			depLabel := m.Label
			depLabel = depLabel.Rel(from.Repo, from.Pkg)
			deps = append(deps, depLabel.String())
		}
	}
	sort.Strings(deps)
	if len(deps) > 0 {
		r.SetAttr("deps", deps)
	}

}

var kinds = map[string]rule.KindInfo{
	"java_library": {
		NonEmptyAttrs:  map[string]bool{"srcs": true, "deps": true},
		MergeableAttrs: map[string]bool{"srcs": true},
		ResolveAttrs: map[string]bool{
			"deps":         true,
			"runtime_deps": true,
		},
	},
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (e *Extension) Kinds() map[string]rule.KindInfo {
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (e *Extension) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested
// in depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a
// struct to avoid breaking implementations in the future when new
// fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.

//go:embed analysis.scm
var analysisQuery []byte

func (e *Extension) GenerateRules(args language.GenerateArgs) language.GenerateResult {

	var rules []*rule.Rule
	var imports []interface{}

	for _, f := range args.RegularFiles {
		if !javaSourceFile(f) {
			continue
		}

		name := strings.TrimSuffix(f, fileType)
		r := rule.NewRule("java_library", name)

		r.SetAttr("srcs", []string{f})
		fullPath := filepath.Join(args.Dir, f)
		loads, err := e.getTreeSitterJavaFileLoads(fullPath)
		if err != nil {
			log.Printf("%s: contains syntax errors: %v", fullPath, err)
		}
		rules = append(rules, r)
		imports = append(imports, loads)

	}
	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}

func javaSourceFile(f string) bool {
	return strings.HasSuffix(f, fileType)
}

func (e *Extension) getTreeSitterJavaFileLoads(path string) ([]string, error) {
	f, err := os.ReadFile(path)

	if err != nil {
		return nil, errors.New("error opening file")
	}

	tree, err := e.parser.ParseCtx(context.Background(), nil, f)

	if err != nil {
		return nil, errors.New("parse tree error")
	}

	q, err := sitter.NewQuery(analysisQuery, java.GetLanguage())
	if err != nil {
		return nil, errors.New("query init failure")
	}
	qc := sitter.NewQueryCursor()
	qc.Exec(q, tree.RootNode())

	var ret []string
	for {
		m, ok := qc.NextMatch()
		if !ok {
			break
		}

		for _, c := range m.Captures {
			// Deal with imports for now
			if q.CaptureNameForId(c.Index) != "import" {
				continue
			}
			log.Printf("%s", c.Node.Content(f))
			ret = append(ret, c.Node.Content(f))
		}
	}
	return ret, nil
}

// Fix repairs deprecated usage of language-specific rules in f. This is
// called before the file is indexed. Unless c.ShouldFix is true, fixes
// that delete or rename rules should not be performed.
func (e *Extension) Fix(c *config.Config, f *rule.File) {
}
